server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    #注册成ip
    #prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    eureka-server-u-r-l-context: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eureka-server


